name: Congratulations

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  Congratulation:

    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/first-interaction@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "We're grateful you made your first issue notification. You can be sure that a response will be made as soon as possible."
        pr-message: "We're grateful you made your first pull request notification. You can be sure that a response will be made as soon as possible."